### ISSUE TITLE
Mobile Navbar starts open

### ISSUE THREAD

**Issue by brookslobe** [leedsjb/info343-group-project#27]
Start in a large window.  Downsize the window width to get the mobile view.  Depending on the page that's being viewed, the mobile hamburger navbar initially displays as open.

**Comment by briluu** [comment]
I can explain the reasoning behind this, its pretty simple. If you already know why, don't bother to read below :) because I'm gonna explain for others.
Every time you click a link on the navbar, it toggles the elements with the class 'collapse', so for our case it would be the div with our navbar links. So when we click links on the navbar on a large window, it's collapsing and uncollapsing the 'mobile navbar version' (you will see the navbar actually flicker when that happens). Under the hood, the 'navbar mobile version' will toggle on and off so if you clicked it in the right order, it'll display as open when you switch to mobile.
As for fixing it, no idea. I gave an attempt, looked up some resources and tried an easy fix but no luck.

**Comment by leedsjb** [comment]
```
<li class="navNames" data-toggle="collapse" data-target=".navbar-collapse"> <a ui-sref="home">Home</a></li>
```

Should have been (note addition of .in):

```
<li class="navNames" data-toggle="collapse" data-target=".navbar-collapse.in"> <a ui-sref="home">Home</a></li>
```

Answer **buried** on this page:
http://stackoverflow.com/questions/16680543/hide-twitter-bootstrap-nav-collapse-on-click
